Import('env')

program = env.Program(target='test',
                      source=Glob('*.cpp'),
                      LIBS=['gtest',
                            'gflags',
                            'glog',
                            'boost_filesystem',
                            'boost_system',
                            'mysqlclient_r'])

[env.Command(target='run-test',
             source=p,
             action=p.abspath) for p in program]

# vim:ft=python ts=4 sw=4 et
