Import('env')
Import('libs')

test_libs = libs + ['boost_unit_test_framework']

program = env.Program(target='test',
                      source=[env.Glob('*.cpp')],
                      LIBS=test_libs)

[env.Command(target='run-test',
             source=p,
             action=p.abspath) for p in program]

# vim:ft=python ts=4 sw=4 et
