Import('env')
Import('libs')

utils = env.Object(source='utils.cpp')

[env.Program(target=example,
             source=['%s.cpp' % example, utils],
             LIBS=libs)
 for example in ['async_connect',
                 'async_execute',
                 'async_multi_query',
                 'async_single_query',
                 'blocking_connect',
                 'blocking_execute',
                 'blocking_multi_query',
                 'blocking_single_query']]

# vim:ft=python sw=4 ts=4 tw=80 et
